name: Workflow Sushi Tests gitHubpages

permissions:
  contents: write  # Donne l'autorisation d'écriture sur le dépôt (nécessaire pour pousser des commits, créer des tags, etc.)


  
on:
  workflow_call:
  push:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
jobs:
  run-sushi-tests_gitHubPages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:      
          path: igSource
      - uses: ansforge/IG-workflows@main
        with:      
          repo_ig: "./igSource"   
          github_page: "true"
          github_page_token: ${{ secrets.GITHUB_TOKEN }}
          bake: "false"
          validator_cli: "false"
          generate_testscript: "false"
          generate_plantuml : "false"